[package]
name = "sdaa_data"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version ='^4.5.18', features = ['derive']}
realfft = "3.4.0"
rustfft = "6.2.0"
tokio = {version="1.44.1", features=["full"]}
lockfree-object-pool = '0.1.3'
crossbeam = '0.8.4'
rayon='1.10.0'
chrono='0.4.40'
num='0.4.3'
rand = "0.9.0"
rand_distr='0.5.1'

[profile.release]
opt-level=3
